"""
Seed the vector store with realistic sample posts for demo/testing.
Run: python -m scripts.seed_data notion
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime, timezone, timedelta
from backend.models.post import Post
from backend.ingestion.pipeline import ingest_posts

NOTION_POSTS = [
    Post(
        id="notion_seed_001",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed001",
        title="Notion is way too complicated for new users",
        body="I've tried to get into Notion multiple times and every time I give up after a week. The onboarding just throws you into a blank page with no guidance. I spent 2 hours watching YouTube tutorials just to build a basic task list. Compare this to Todoist where I was productive on day one. The learning curve is absolutely brutal.",
        author="frustrated_user_01",
        score=847,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        subreddit="Notion",
        sentiment_score=-0.7,
    ),
    Post(
        id="notion_seed_002",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/productivity/comments/seed002",
        title="The template gallery is overwhelming and useless",
        body="Every time I open Notion's template gallery I get decision paralysis. There are thousands of templates and none of them are exactly what I need. I end up spending more time looking at templates than actually working. I wish there was a simple 'start here' path for new users instead of this giant maze.",
        author="productivity_seeker",
        score=621,
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
        subreddit="productivity",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_003",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="Great concept but mobile experience is terrible",
        body="Love what Notion tries to do but the mobile app is a disaster. It's slow to load, the editor is clunky on phone screens, and half the features from desktop are missing. I've switched to using it only on my laptop because the mobile app frustrates me so much.",
        author="MobileUserJoe",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        app_id="1232780281",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_004",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed004",
        title="New user here - what's the best way to get started?",
        body="Just signed up for Notion after seeing it everywhere. Opened it and stared at a blank page for 20 minutes. There's no tutorial, no quick win, nothing. I feel like I need a degree to use this thing. How did you all get started? I almost quit immediately.",
        author="newbie_notion",
        score=334,
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
        subreddit="Notion",
        sentiment_score=-0.3,
    ),
    Post(
        id="notion_seed_005",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed005",
        title="Why Notion's onboarding fails — and how to fix it",
        body="Notion is powerful but its onboarding is a perfect example of a product that shows off features instead of delivering value. The first session should give users one clear win. Instead you get a blank canvas and a 47-item template gallery. The drop-off rate on day 1 must be enormous.",
        author="hn_tech_critic",
        score=412,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        sentiment_score=-0.4,
    ),
    Post(
        id="notion_seed_006",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed006",
        title="Notion offline mode is basically broken",
        body="I travel for work and Notion is completely useless without internet. I've lost edits three times because I was on a spotty connection. The offline sync is just fundamentally broken. Obsidian does this perfectly with local files. Why can't Notion figure this out?",
        author="travel_worker_22",
        score=512,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="Notion",
        sentiment_score=-0.8,
    ),
    Post(
        id="notion_seed_007",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="5 stars — changed how I work",
        body="Notion has completely transformed my productivity. Once I got past the initial learning curve it's absolutely incredible. I use it for my personal CRM, project management, notes, and journaling. The flexibility is unmatched. Nothing else comes close.",
        author="PowerUserPaul",
        score=5,
        created_at=datetime.now(timezone.utc) - timedelta(days=3),
        app_id="1232780281",
        sentiment_score=0.9,
    ),
    Post(
        id="notion_seed_008",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/productivity/comments/seed008",
        title="Notion vs Trello for beginners?",
        body="Switched from Trello to Notion last month. Trello has you set up and productive in 5 minutes. Notion took me three weeks to get comfortable with. The power is there but the onboarding gap is massive. Most of my team gave up and went back to Trello. The quick win problem is real — Trello gives you a board immediately, Notion gives you... nothing.",
        author="team_lead_rj",
        score=289,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        subreddit="productivity",
        sentiment_score=-0.2,
    ),
    Post(
        id="notion_seed_009",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed009",
        title="Ask HN: Why does everyone at startups use Notion?",
        body="The main appeal is the flexibility — it's basically a Lego set for productivity. But that same flexibility is also its biggest weakness for onboarding. New employees at companies using Notion always struggle for the first month. There should be a simplified mode that hides advanced features until you're ready.",
        author="startup_employee",
        score=156,
        created_at=datetime.now(timezone.utc) - timedelta(days=45),
        sentiment_score=0.1,
    ),
    Post(
        id="notion_seed_010",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed010",
        title="Notion performance is getting worse",
        body="I've been a Notion user for 3 years and the performance has noticeably degraded over the past year. Pages with large databases take 5-8 seconds to load. The app feels sluggish constantly. They keep adding features instead of fixing the core performance. My Notion workspace has become so slow it's affecting my work.",
        author="longtime_user_k",
        score=743,
        created_at=datetime.now(timezone.utc) - timedelta(days=7),
        subreddit="Notion",
        sentiment_score=-0.75,
    ),
    Post(
        id="notion_seed_011",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="Too complex, too slow",
        body="I keep coming back hoping it's gotten better and it never has. The app is slow. Everything takes too many clicks. I wanted a note-taking app and got a complexity maze. 2 stars because the idea is good.",
        author="disappointed_app_user",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=2),
        app_id="1232780281",
        sentiment_score=-0.6,
    ),
    Post(
        id="notion_seed_012",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed012",
        title="The AI features are actually great but nobody talks about it",
        body="People complain about Notion constantly but the AI features that dropped last year are genuinely impressive. Auto-fill databases with AI, summarize pages, translate content — all incredibly useful once set up. The onboarding to AI features is equally bad but the features themselves are fantastic.",
        author="notion_ai_fan",
        score=201,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        subreddit="Notion",
        sentiment_score=0.6,
    ),
    Post(
        id="notion_seed_013",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/software/comments/seed013",
        title="Why I quit Notion after 2 years",
        body="The breaking point was realizing I spend more time managing my Notion workspace than actually doing work. It became its own project. The maintenance burden is real — you have to constantly reorganize, update templates, clean up databases. I switched to a simple markdown folder and never looked back. Notion is great for people who enjoy building systems, terrible for people who just want to get things done.",
        author="ex_notion_user",
        score=987,
        created_at=datetime.now(timezone.utc) - timedelta(days=40),
        subreddit="software",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_014",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed014",
        title="Notion database formulas are a nightmare",
        body="If you try to do anything complex with Notion databases, the formula syntax is opaque and poorly documented. It feels like they designed it for simple use cases and then bolted on complexity. Missing basic operations, no real debugging tools, error messages are useless. Airtable handles this much better.",
        author="formula_frustrated",
        score=88,
        created_at=datetime.now(timezone.utc) - timedelta(days=60),
        sentiment_score=-0.65,
    ),
    Post(
        id="notion_seed_015",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed015",
        title="Best Notion setup for students?",
        body="As a college student Notion is perfect for class notes and project tracking. I've built a GPA tracker, study schedule, and reading list all in one workspace. The learning curve was steep but worth it. It's free for students too which is a huge plus. I've recommended it to everyone in my dorm.",
        author="college_notion_user",
        score=445,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="Notion",
        sentiment_score=0.75,
    ),
]


LINEAR_POSTS = [
    Post(
        id="linear_seed_001",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/devtools/comments/lseed001",
        title="Linear is hands down the fastest project tracker I've used",
        body="Switched our team from Jira to Linear 6 months ago. The speed difference is night and day — everything is instant. Keyboard shortcuts for everything, CMD+K to jump anywhere. Our sprint planning sessions went from 90 minutes to 30. The only thing I miss is Jira's advanced JQL queries for complex filtering.",
        author="devtools_fan",
        score=723,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="devtools",
        sentiment_score=0.85,
    ),
    Post(
        id="linear_seed_002",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/startups/comments/lseed002",
        title="Linear pricing is getting hard to justify",
        body="We love Linear but at $8/user/month it adds up fast for a 50-person startup. We're paying almost $5k/year for issue tracking. Jira is cheaper at scale and GitHub Issues is free. The UX is amazing but the pricing doesn't scale well for growing teams. Wish they had a startup discount.",
        author="startup_cfo",
        score=412,
        created_at=datetime.now(timezone.utc) - timedelta(days=20),
        subreddit="startups",
        sentiment_score=-0.3,
    ),
    Post(
        id="linear_seed_003",
        source="hackernews",
        product="linear",
        url="https://news.ycombinator.com/item?id=lseed003",
        title="Linear's GitHub integration is seamless",
        body="The bi-directional sync between Linear issues and GitHub PRs is the best I've seen. Auto-closing issues when PRs merge, branch name generation, status updates — it all just works. Compare this to Jira where the GitHub integration feels bolted on. Linear clearly built for developer workflows first.",
        author="hn_dev_ops",
        score=287,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        sentiment_score=0.7,
    ),
    Post(
        id="linear_seed_004",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/projectmanagement/comments/lseed004",
        title="Linear lacks basic reporting features",
        body="Linear is great for developers but terrible for project managers who need to report to leadership. No burndown charts, no velocity tracking, no customizable dashboards. I have to export data to Google Sheets every week to build reports. For a tool at this price point, the reporting gap is embarrassing.",
        author="pm_frustrated",
        score=534,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        subreddit="projectmanagement",
        sentiment_score=-0.6,
    ),
    Post(
        id="linear_seed_005",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/devtools/comments/lseed005",
        title="Cycles vs Sprints — Linear gets it right",
        body="Linear's cycles are sprints done right. Auto-rollover of incomplete issues, triage inbox to prevent scope creep, and the cooldown period concept is genius. We tried going back to Jira for a quarter and the team revolted. Linear's opinionated workflow actually makes teams more productive.",
        author="agile_coach_42",
        score=356,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        subreddit="devtools",
        sentiment_score=0.8,
    ),
    Post(
        id="linear_seed_006",
        source="hackernews",
        product="linear",
        url="https://news.ycombinator.com/item?id=lseed006",
        title="Linear's mobile app is an afterthought",
        body="The desktop and web experience is incredible but the mobile app feels like a prototype. Can't create sub-issues, can't edit descriptions properly, search is limited. For a team distributed across timezones I need to triage on mobile during off-hours. This is a dealbreaker for some workflows.",
        author="remote_eng_lead",
        score=198,
        created_at=datetime.now(timezone.utc) - timedelta(days=35),
        sentiment_score=-0.5,
    ),
    Post(
        id="linear_seed_007",
        source="appstore",
        product="linear",
        url="https://apps.apple.com/us/app/linear/id1507926311",
        title="Beautiful app but limited",
        body="The design is gorgeous and it's fast but the mobile app is missing too many features. Can't manage projects, can't view roadmaps, custom views don't sync from desktop. It's basically a read-only companion app with basic triage. Needs serious work.",
        author="MobileDevLead",
        score=3,
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
        app_id="1507926311",
        sentiment_score=-0.4,
    ),
    Post(
        id="linear_seed_008",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/SaaS/comments/lseed008",
        title="Linear's API is developer-friendly but docs need work",
        body="The GraphQL API is powerful and well-designed. Built a custom Slack bot for our team notifications in a day. However the documentation has gaps — some mutations aren't documented and the webhook payload examples are incomplete. Had to reverse-engineer a few things by inspecting network requests in the web app.",
        author="api_builder",
        score=167,
        created_at=datetime.now(timezone.utc) - timedelta(days=40),
        subreddit="SaaS",
        sentiment_score=0.3,
    ),
    Post(
        id="linear_seed_009",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/devtools/comments/lseed009",
        title="No guest access in Linear is a dealbreaker",
        body="We can't invite clients or external contractors to Linear without giving them a full paid seat. Jira and Asana both have guest/viewer roles. For an agency this means we either pay for seats clients barely use or maintain a separate tool for client-facing work. Really frustrating limitation.",
        author="agency_dev_lead",
        score=445,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="devtools",
        sentiment_score=-0.65,
    ),
    Post(
        id="linear_seed_010",
        source="hackernews",
        product="linear",
        url="https://news.ycombinator.com/item?id=lseed010",
        title="Linear's keyboard-first UX is a masterclass",
        body="Every interaction in Linear can be done without touching the mouse. CMD+K, then type what you want. Create issue, assign, set priority, add to cycle — all from keyboard. For developers who live in terminals this feels natural. It's the Vim of project management tools. No other PM tool comes close to this level of keyboard optimization.",
        author="keyboard_warrior",
        score=503,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        sentiment_score=0.9,
    ),
    Post(
        id="linear_seed_011",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/startups/comments/lseed011",
        title="Switched from Linear back to GitHub Issues",
        body="Controversial take: GitHub Issues + Projects is now good enough for most small teams. We dropped Linear after realizing we were paying $400/month for features we didn't use. The new GitHub Projects views, custom fields, and automation cover 80% of what we needed. Linear is premium but the free alternative has caught up significantly.",
        author="pragmatic_cto",
        score=678,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        subreddit="startups",
        sentiment_score=-0.2,
    ),
    Post(
        id="linear_seed_012",
        source="appstore",
        product="linear",
        url="https://apps.apple.com/us/app/linear/id1507926311",
        title="Best issue tracker, period",
        body="Nothing comes close to Linear for developer teams. Fast, beautiful, opinionated in the right ways. Our engineering velocity measurably improved after switching from Jira. The triage workflow alone saved us hours per week. Worth every penny of the subscription.",
        author="HappyEngManager",
        score=5,
        created_at=datetime.now(timezone.utc) - timedelta(days=3),
        app_id="1507926311",
        sentiment_score=0.9,
    ),
    Post(
        id="linear_seed_013",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/devtools/comments/lseed013",
        title="Linear needs better permissions and roles",
        body="Our org has 200+ engineers and the permission model is too flat. Everyone can see every team's issues. No way to restrict visibility of sensitive projects (security, HR tooling). Enterprise features are coming but too slowly. We might have to go back to Jira just for access controls.",
        author="enterprise_eng",
        score=289,
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
        subreddit="devtools",
        sentiment_score=-0.5,
    ),
    Post(
        id="linear_seed_014",
        source="appstore",
        product="linear",
        url="https://apps.apple.com/us/app/linear/id1507926311",
        title="Crashes constantly on iPad",
        body="App crashes every time I try to open a project view on my iPad Pro. Works fine on iPhone but iPad experience is broken. Been like this for months across multiple updates. Submitted bug reports, no response. Disappointing for a company that prides itself on quality.",
        author="iPadEngineer",
        score=1,
        created_at=datetime.now(timezone.utc) - timedelta(days=7),
        app_id="1507926311",
        sentiment_score=-0.8,
    ),
    Post(
        id="linear_seed_015",
        source="reddit",
        product="linear",
        url="https://reddit.com/r/devtools/comments/lseed015",
        title="Linear's roadmap feature changed how we plan",
        body="The roadmap view with timeline and dependencies finally made product planning visual for our team. PMs can see cross-team dependencies, engineers can see where their work fits in the bigger picture. It's not as powerful as dedicated roadmap tools but having it integrated with issues is a huge win.",
        author="product_eng_lead",
        score=312,
        created_at=datetime.now(timezone.utc) - timedelta(days=14),
        subreddit="devtools",
        sentiment_score=0.7,
    ),
]

FIGMA_POSTS = [
    Post(
        id="figma_seed_001",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed001",
        title="Figma performance tanks with large files",
        body="I'm working on a design system with 500+ components and Figma has become unusable. Switching between pages takes 10+ seconds, auto-layout recalculations freeze the entire canvas, and my MacBook Pro fans spin up like a jet engine. We had to split our design system across 4 files which defeats the purpose.",
        author="design_system_lead",
        score=891,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        subreddit="FigmaDesign",
        sentiment_score=-0.7,
    ),
    Post(
        id="figma_seed_002",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/UI_Design/comments/fseed002",
        title="Dev mode is a game changer for handoff",
        body="Figma's Dev Mode has completely eliminated our design-to-code handoff friction. Developers can inspect spacing, grab CSS, see component props, and compare to code — all without leaving Figma. Our sprint velocity improved because developers stopped asking designers for specs. Worth the extra cost.",
        author="ui_dev_collab",
        score=654,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        subreddit="UI_Design",
        sentiment_score=0.85,
    ),
    Post(
        id="figma_seed_003",
        source="hackernews",
        product="figma",
        url="https://news.ycombinator.com/item?id=fseed003",
        title="Figma's pricing changes are pushing freelancers away",
        body="The new seat-based pricing killed it for freelancers. I used to pay $12/month for Professional and now the same features require an Organization plan at $45/editor/month just to get branching and design system analytics. Freelancers and small studios are being priced out. Penpot is looking more attractive every day.",
        author="freelance_designer",
        score=567,
        created_at=datetime.now(timezone.utc) - timedelta(days=20),
        sentiment_score=-0.6,
    ),
    Post(
        id="figma_seed_004",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed004",
        title="Auto-layout in Figma is incredible but confusing",
        body="Auto-layout is the most powerful feature in Figma but the mental model is confusing for new users. Absolute positioning within auto-layout, min/max width constraints, fill vs hug vs fixed — there are so many options that simple layouts become complex. The documentation is good but the UX could be more intuitive.",
        author="junior_designer",
        score=423,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="FigmaDesign",
        sentiment_score=-0.2,
    ),
    Post(
        id="figma_seed_005",
        source="appstore",
        product="figma",
        url="https://apps.apple.com/us/app/figma/id1152747299",
        title="iPad app is beautiful but limited",
        body="The iPad app looks great and FigJam works well but you can't do real design work on it. No pen tool, no component editing, limited prototyping. It's essentially a viewing and annotation tool. For designers who want to sketch on iPad and refine on desktop, the workflow is broken.",
        author="iPadDesigner",
        score=3,
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
        app_id="1152747299",
        sentiment_score=-0.4,
    ),
    Post(
        id="figma_seed_006",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed006",
        title="Real-time collaboration is why we'll never leave Figma",
        body="Tried every design tool and nothing matches Figma's multiplayer experience. Watching cursors move, live comments, version history with branching — it's Google Docs for design. We had 8 designers working on the same file during a design sprint and it was magical. This is Figma's real moat.",
        author="design_director",
        score=778,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        subreddit="FigmaDesign",
        sentiment_score=0.9,
    ),
    Post(
        id="figma_seed_007",
        source="hackernews",
        product="figma",
        url="https://news.ycombinator.com/item?id=fseed007",
        title="Figma variables and design tokens are half-baked",
        body="Variables were announced with huge fanfare but the implementation is frustratingly incomplete. No string variables for text content, no support for composite tokens, can't reference variables in all properties. Our design system team has been waiting over a year for these gaps to close. The foundation is good but shipping incomplete features creates technical debt.",
        author="design_systems_eng",
        score=345,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        sentiment_score=-0.5,
    ),
    Post(
        id="figma_seed_008",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/webdev/comments/fseed008",
        title="Figma to code is still not solved",
        body="Despite Dev Mode and all the plugins, converting Figma designs to production code is still painful. Auto-generated code is messy, doesn't use your component library, and ignores responsive behavior. We still manually build every screen. The promise of design-to-code feels like it's always 'almost there' but never actually arrives.",
        author="frontend_dev_frustrated",
        score=534,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        subreddit="webdev",
        sentiment_score=-0.4,
    ),
    Post(
        id="figma_seed_009",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed009",
        title="Offline mode is non-existent",
        body="Figma is entirely cloud-dependent. Lost internet for 2 hours during a flight and couldn't access any of my files. No offline mode, no local cache, nothing. For a tool that designers depend on daily this is unacceptable. Sketch at least works offline. Cloud-first shouldn't mean cloud-only.",
        author="traveling_designer",
        score=612,
        created_at=datetime.now(timezone.utc) - timedelta(days=7),
        subreddit="FigmaDesign",
        sentiment_score=-0.7,
    ),
    Post(
        id="figma_seed_010",
        source="appstore",
        product="figma",
        url="https://apps.apple.com/us/app/figma/id1152747299",
        title="5 stars — indispensable for our team",
        body="Figma replaced Sketch, InVision, Zeplin, and Abstract for our team. One tool that does design, prototyping, handoff, and collaboration. The plugin ecosystem is incredible. We saved $2000/month consolidating tools. Best design tool ever made.",
        author="DesignTeamLead",
        score=5,
        created_at=datetime.now(timezone.utc) - timedelta(days=2),
        app_id="1152747299",
        sentiment_score=0.95,
    ),
    Post(
        id="figma_seed_011",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed011",
        title="Prototyping in Figma is powerful but has weird limitations",
        body="You can build incredibly complex prototypes but then hit random walls. No conditional logic without hacks, scroll position doesn't persist between frames, and video embedding is janky. For simple click-through prototypes it's perfect but for anything interactive you need to switch to Framer or ProtoPie.",
        author="prototyping_pro",
        score=298,
        created_at=datetime.now(timezone.utc) - timedelta(days=35),
        subreddit="FigmaDesign",
        sentiment_score=-0.3,
    ),
    Post(
        id="figma_seed_012",
        source="hackernews",
        product="figma",
        url="https://news.ycombinator.com/item?id=fseed012",
        title="Figma's plugin API is excellent",
        body="Built a custom accessibility checker plugin for our org in a weekend. The plugin API is well-documented, TypeScript-first, and the sandbox model is smart. Community plugins cover most needs but being able to build internal tools on top of Figma is underrated. It's becoming a platform, not just a tool.",
        author="design_toolsmith",
        score=234,
        created_at=datetime.now(timezone.utc) - timedelta(days=42),
        sentiment_score=0.75,
    ),
    Post(
        id="figma_seed_013",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/FigmaDesign/comments/fseed013",
        title="Memory usage is out of control",
        body="Figma in Chrome uses 4-6GB of RAM with our design files open. Add a few other tabs and my 16GB MacBook is swapping constantly. The desktop app isn't much better. For a browser-based tool the memory footprint is absurd. They need to work on performance optimization seriously.",
        author="ram_starved_designer",
        score=445,
        created_at=datetime.now(timezone.utc) - timedelta(days=14),
        subreddit="FigmaDesign",
        sentiment_score=-0.6,
    ),
    Post(
        id="figma_seed_014",
        source="reddit",
        product="figma",
        url="https://reddit.com/r/UI_Design/comments/fseed014",
        title="Figma AI features feel forced",
        body="The new AI-powered features feel like they were added because every SaaS needs AI now, not because they solve real problems. AI-generated mockups are generic and unusable for production work. I'd rather they focused on fixing variables and improving performance than chasing the AI hype.",
        author="skeptical_designer",
        score=567,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="UI_Design",
        sentiment_score=-0.4,
    ),
    Post(
        id="figma_seed_015",
        source="appstore",
        product="figma",
        url="https://apps.apple.com/us/app/figma/id1152747299",
        title="Crashes on large files",
        body="Every time I try to open our main design file on the iPad app it crashes. Works fine for smaller files but anything with 50+ frames is unstable. Filed multiple bug reports over 3 months with no fix. Frustrating because I want to review designs during meetings on my iPad.",
        author="CrashReporter",
        score=1,
        created_at=datetime.now(timezone.utc) - timedelta(days=4),
        app_id="1152747299",
        sentiment_score=-0.7,
    ),
]

SLACK_POSTS = [
    Post(
        id="slack_seed_001",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed001",
        title="Slack notifications are destroying my focus",
        body="Between channels, DMs, threads, and @mentions I get 200+ Slack notifications per day. The notification settings are granular but managing them across 50 channels is a full-time job. I've started closing Slack for 2-hour focus blocks and my productivity doubled. The tool designed for communication is actually killing productivity.",
        author="focus_mode_advocate",
        score=1234,
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
        subreddit="Slack",
        sentiment_score=-0.6,
    ),
    Post(
        id="slack_seed_002",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/sysadmin/comments/sseed002",
        title="Slack's memory usage is insane for a chat app",
        body="Slack desktop app uses 1.5-2GB of RAM just sitting idle. It's an Electron app so not surprising but for a text messaging tool this is absurd. My actual IDE uses less memory. Teams is bad too but at least it's included with our Office license. Slack needs a native rewrite badly.",
        author="sysadmin_optimist",
        score=876,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        subreddit="sysadmin",
        sentiment_score=-0.7,
    ),
    Post(
        id="slack_seed_003",
        source="hackernews",
        product="slack",
        url="https://news.ycombinator.com/item?id=sseed003",
        title="Slack Connect is genuinely useful for B2B",
        body="Slack Connect replaced email for all our vendor and client communications. Shared channels mean everyone has context, decisions are documented, and onboarding new team members to a client relationship is instant. This feature alone justifies the Business+ plan for B2B companies. Nothing else does cross-org messaging this well.",
        author="b2b_operations",
        score=345,
        created_at=datetime.now(timezone.utc) - timedelta(days=20),
        sentiment_score=0.8,
    ),
    Post(
        id="slack_seed_004",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed004",
        title="Search in Slack is embarrassingly bad",
        body="Finding old messages in Slack is like searching for a needle in a haystack. The search doesn't understand context, filters are confusing, and results are sorted by some algorithm that never shows what I want first. I know the conversation happened but I can't find it. For a tool that stores all our company knowledge, the search is its weakest feature.",
        author="search_frustrated",
        score=967,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="Slack",
        sentiment_score=-0.65,
    ),
    Post(
        id="slack_seed_005",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed005",
        title="Threads are great in theory, terrible in practice",
        body="The thread feature was supposed to reduce channel noise but instead created two places to check for messages. People reply in threads sometimes and in the channel other times. Important context gets buried in threads nobody follows. The 'Also send to channel' checkbox just adds confusion. Threads need a fundamental rethink.",
        author="thread_skeptic",
        score=743,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="Slack",
        sentiment_score=-0.5,
    ),
    Post(
        id="slack_seed_006",
        source="appstore",
        product="slack",
        url="https://apps.apple.com/us/app/slack/id618783545",
        title="Mobile app has gotten much better",
        body="The Slack mobile app used to be painful but the recent updates have been solid. Huddles work well on mobile now, the notification grouping is smarter, and switching between workspaces is faster. Still not perfect but it's finally usable for staying connected on the go. 4 stars.",
        author="MobileWorker",
        score=4,
        created_at=datetime.now(timezone.utc) - timedelta(days=3),
        app_id="618783545",
        sentiment_score=0.5,
    ),
    Post(
        id="slack_seed_007",
        source="hackernews",
        product="slack",
        url="https://news.ycombinator.com/item?id=sseed007",
        title="Slack's free tier changes killed it for open source communities",
        body="The 90-day message history limit on the free tier destroyed years of open source community knowledge. Projects that used Slack for community support lost their entire searchable history overnight. Many migrated to Discord which offers unlimited history for free. Slack chose enterprise revenue over community goodwill.",
        author="oss_maintainer",
        score=892,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        sentiment_score=-0.8,
    ),
    Post(
        id="slack_seed_008",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed008",
        title="Huddles replaced 80% of our Zoom calls",
        body="Slack Huddles is an underrated feature. Quick audio calls that start instantly without scheduling a meeting, sharing screen, and people can drop in/out. We use it for quick syncs, pair programming, and rubber duck debugging. Replaced most of our impromptu Zoom meetings. The low-friction nature makes people actually use it.",
        author="huddle_fan",
        score=456,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        subreddit="Slack",
        sentiment_score=0.75,
    ),
    Post(
        id="slack_seed_009",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/productivity/comments/sseed009",
        title="Slack is where productivity goes to die",
        body="Every company I've worked at treats Slack as a real-time communication tool where you're expected to respond within minutes. It creates a culture of constant interruption. Important decisions get made in ephemeral chat messages instead of documented async processes. Slack enables bad communication habits and companies blame the tool instead of fixing the culture.",
        author="async_advocate",
        score=1567,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        subreddit="productivity",
        sentiment_score=-0.5,
    ),
    Post(
        id="slack_seed_010",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed010",
        title="The integration ecosystem is Slack's real value",
        body="We have 40+ integrations running in Slack — GitHub notifications, PagerDuty alerts, Jira updates, deploy notifications, customer support escalations. Slack has become our single pane of glass for everything. No other chat tool has this depth of integrations. It's not just a chat app anymore, it's an operational hub.",
        author="integrations_power_user",
        score=534,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        subreddit="Slack",
        sentiment_score=0.7,
    ),
    Post(
        id="slack_seed_011",
        source="appstore",
        product="slack",
        url="https://apps.apple.com/us/app/slack/id618783545",
        title="Battery drain is terrible",
        body="Slack drains my iPhone battery faster than any other app. With background refresh enabled it uses 20-25% of my daily battery. Had to disable notifications during off-hours just to make it through the day. A messaging app shouldn't need this much power. Very frustrating.",
        author="BatteryDead",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=6),
        app_id="618783545",
        sentiment_score=-0.6,
    ),
    Post(
        id="slack_seed_012",
        source="hackernews",
        product="slack",
        url="https://news.ycombinator.com/item?id=sseed012",
        title="Slack AI summarization is surprisingly good",
        body="Was skeptical about Slack AI but the channel summarization feature is genuinely useful. After a week of vacation I could catch up on every channel in 20 minutes instead of scrolling through thousands of messages. Thread summaries help for long discussions too. First AI feature in a workplace tool that I actually use daily.",
        author="ai_convert",
        score=278,
        created_at=datetime.now(timezone.utc) - timedelta(days=14),
        sentiment_score=0.7,
    ),
    Post(
        id="slack_seed_013",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed013",
        title="Pricing is obscene for large orgs",
        body="$12.50/user/month for Pro means we're paying $150k/year for chat. Business+ is $17.50/user. That's more than most of our actual productivity tools combined. And the free tier is now useless with the message history limit. Slack has become one of our top 5 SaaS costs and it's literally just messaging.",
        author="it_budget_manager",
        score=823,
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
        subreddit="Slack",
        sentiment_score=-0.55,
    ),
    Post(
        id="slack_seed_014",
        source="reddit",
        product="slack",
        url="https://reddit.com/r/Slack/comments/sseed014",
        title="Workflow Builder is surprisingly powerful",
        body="Built an entire employee onboarding flow in Workflow Builder without writing code. New hire fills out a form, gets added to the right channels, receives a welcome message with links, and their manager gets notified. Saved our HR team 2 hours per new hire. Most people don't even know this feature exists.",
        author="workflow_builder_fan",
        score=345,
        created_at=datetime.now(timezone.utc) - timedelta(days=16),
        subreddit="Slack",
        sentiment_score=0.8,
    ),
    Post(
        id="slack_seed_015",
        source="appstore",
        product="slack",
        url="https://apps.apple.com/us/app/slack/id618783545",
        title="Constant connection issues",
        body="The app shows 'connecting' at least 3-4 times per day. Messages arrive late or not at all until I force-quit and reopen. On the same wifi my other apps work perfectly. Been happening for months across multiple iOS versions. Can't rely on it for urgent communications anymore.",
        author="ConnectionDropper",
        score=1,
        created_at=datetime.now(timezone.utc) - timedelta(days=9),
        app_id="618783545",
        sentiment_score=-0.75,
    ),
]

GITHUB_POSTS = [
    Post(
        id="github_seed_001",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed001",
        title="GitHub Copilot has completely changed how I code",
        body="After 6 months with Copilot I can't imagine coding without it. It handles boilerplate, suggests test cases I wouldn't think of, and even catches bugs in real-time. My velocity is up at least 30%. The tab-completion feels like having a junior dev pair programming with you 24/7. Best $10/month I spend.",
        author="copilot_convert",
        score=1456,
        created_at=datetime.now(timezone.utc) - timedelta(days=7),
        subreddit="github",
        sentiment_score=0.9,
    ),
    Post(
        id="github_seed_002",
        source="reddit",
        product="github",
        url="https://reddit.com/r/programming/comments/gseed002",
        title="GitHub Actions pricing is getting ridiculous",
        body="We're spending $800/month on GitHub Actions for a medium-sized team. The free minutes ran out in the first week and the per-minute pricing adds up fast for CI/CD. Self-hosted runners help but add maintenance overhead. GitLab gives you 400 minutes free and their runners are faster. GitHub is nickel-and-diming on Actions.",
        author="ci_cd_accountant",
        score=876,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        subreddit="programming",
        sentiment_score=-0.6,
    ),
    Post(
        id="github_seed_003",
        source="hackernews",
        product="github",
        url="https://news.ycombinator.com/item?id=gseed003",
        title="GitHub's code search is finally excellent",
        body="The new code search (cs.github.com) is a massive improvement. Regex support, language filters, path filters, and it's fast across all of GitHub. Finding code examples across open source repos is now incredibly efficient. This was GitHub's biggest weakness for years and they finally nailed it.",
        author="code_searcher",
        score=567,
        created_at=datetime.now(timezone.utc) - timedelta(days=20),
        sentiment_score=0.8,
    ),
    Post(
        id="github_seed_004",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed004",
        title="PR review experience needs serious work",
        body="Reviewing large PRs on GitHub is painful. The diff viewer doesn't handle large files well, there's no way to mark files as reviewed and have it persist across force-pushes, and the conversation view mixes resolved and active comments. GitLab and Gerrit both have better code review UX. For the world's largest code platform, the review experience is surprisingly mediocre.",
        author="code_reviewer",
        score=734,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="github",
        sentiment_score=-0.5,
    ),
    Post(
        id="github_seed_005",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed005",
        title="Copilot hallucinations are a real problem",
        body="Copilot is great for simple tasks but it confidently generates code that looks correct but has subtle bugs. It suggested a SQL query with a left join that silently dropped rows, and a regex that missed edge cases. Junior devs on my team accepted suggestions without reviewing them and introduced bugs. The false confidence is dangerous.",
        author="senior_eng_skeptic",
        score=623,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="github",
        sentiment_score=-0.5,
    ),
    Post(
        id="github_seed_006",
        source="hackernews",
        product="github",
        url="https://news.ycombinator.com/item?id=gseed006",
        title="GitHub Projects has quietly become very good",
        body="GitHub Projects v2 with custom fields, views, and automations has reached a point where small teams don't need a separate project management tool. Board view, table view, timeline view — all connected to issues and PRs. Not as polished as Linear but free and deeply integrated. Good enough for 80% of teams.",
        author="minimal_tooling",
        score=445,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        sentiment_score=0.65,
    ),
    Post(
        id="github_seed_007",
        source="appstore",
        product="github",
        url="https://apps.apple.com/us/app/github/id1477376905",
        title="Mobile app is great for triage",
        body="Use the GitHub mobile app daily for reviewing PRs on my commute, triaging issues, and checking CI status. Push notifications for mentions are reliable. Code review on mobile is actually usable with the syntax highlighting. One of the better developer mobile apps out there.",
        author="MobileDevOps",
        score=5,
        created_at=datetime.now(timezone.utc) - timedelta(days=4),
        app_id="1477376905",
        sentiment_score=0.7,
    ),
    Post(
        id="github_seed_008",
        source="reddit",
        product="github",
        url="https://reddit.com/r/programming/comments/gseed008",
        title="GitHub's monopoly on open source is concerning",
        body="90% of open source lives on GitHub which is owned by Microsoft. Single point of failure, vendor lock-in, and they can change terms anytime. The Copilot training controversy showed they'll use your public code for commercial products. We need more viable alternatives. GitLab, Codeberg, and Forgejo exist but network effects keep everyone on GitHub.",
        author="open_source_advocate",
        score=1234,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        subreddit="programming",
        sentiment_score=-0.4,
    ),
    Post(
        id="github_seed_009",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed009",
        title="Dependabot is noisy but essential",
        body="Dependabot creates so many PRs that our repos are constantly flooded with security updates. 20+ PRs per week across our repos. But when it catches a critical vulnerability it's invaluable. The auto-merge for patch updates helps but we need better grouping — one PR per ecosystem instead of one per dependency.",
        author="dependency_manager",
        score=389,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        subreddit="github",
        sentiment_score=0.1,
    ),
    Post(
        id="github_seed_010",
        source="hackernews",
        product="github",
        url="https://news.ycombinator.com/item?id=gseed010",
        title="GitHub Codespaces is underrated",
        body="Spinning up a full dev environment in 90 seconds from any browser is transformative. New team member onboarding went from a full day of setup to 'click this link and start coding.' Pre-built containers mean everyone has identical environments. The pricing per compute hour is fair. This is the future of dev environments.",
        author="cloud_dev_believer",
        score=512,
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
        sentiment_score=0.85,
    ),
    Post(
        id="github_seed_011",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed011",
        title="GitHub Enterprise pricing is outrageous",
        body="$21/user/month for Enterprise Cloud with required annual commitment. For a 500-person org that's over $125k/year. And you still have to pay extra for Actions minutes, Copilot seats, and advanced security. GitLab's comparable tier is cheaper and includes more features. GitHub is riding on market dominance, not value.",
        author="enterprise_buyer",
        score=567,
        created_at=datetime.now(timezone.utc) - timedelta(days=14),
        subreddit="github",
        sentiment_score=-0.55,
    ),
    Post(
        id="github_seed_012",
        source="appstore",
        product="github",
        url="https://apps.apple.com/us/app/github/id1477376905",
        title="Can't merge PRs from mobile",
        body="The app is good for reviewing code but I can't merge PRs, can't run or re-run Actions, and can't edit files. Basic operations that I need when on-call require opening a laptop. For incident response this is a real gap. Please add merge and Actions controls.",
        author="OnCallDev",
        score=3,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        app_id="1477376905",
        sentiment_score=-0.3,
    ),
    Post(
        id="github_seed_013",
        source="reddit",
        product="github",
        url="https://reddit.com/r/programming/comments/gseed013",
        title="Copilot Workspace looks like the future of development",
        body="Just got access to Copilot Workspace and it's impressive. Describe what you want to change in natural language, it creates a plan, edits multiple files, and opens a PR. It's not perfect but for straightforward changes it saves 15-20 minutes. The iteration loop of 'describe, review, refine' feels like the right UX for AI-assisted development.",
        author="ai_tools_explorer",
        score=789,
        created_at=datetime.now(timezone.utc) - timedelta(days=6),
        subreddit="programming",
        sentiment_score=0.8,
    ),
    Post(
        id="github_seed_014",
        source="reddit",
        product="github",
        url="https://reddit.com/r/github/comments/gseed014",
        title="GitHub Issues is still too basic",
        body="After years of updates, GitHub Issues still lacks basic features that Jira and Linear have: custom fields (only recently added and limited), issue types, sprint/cycle management, time tracking. The new Projects help but Issues themselves are glorified markdown files with labels. For serious project management you still need a separate tool.",
        author="pm_on_github",
        score=456,
        created_at=datetime.now(timezone.utc) - timedelta(days=35),
        subreddit="github",
        sentiment_score=-0.4,
    ),
    Post(
        id="github_seed_015",
        source="appstore",
        product="github",
        url="https://apps.apple.com/us/app/github/id1477376905",
        title="Notifications are broken",
        body="Push notifications are unreliable. Sometimes I get them instantly, sometimes 30 minutes late, sometimes not at all. Had to set up email notifications as backup which defeats the purpose of the app. For a company this big, reliable push notifications shouldn't be this hard.",
        author="NotificationWaiter",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=11),
        app_id="1477376905",
        sentiment_score=-0.6,
    ),
]

ALL_PRODUCTS = {
    "notion": NOTION_POSTS,
    "linear": LINEAR_POSTS,
    "figma": FIGMA_POSTS,
    "slack": SLACK_POSTS,
    "github": GITHUB_POSTS,
}


def main():
    product = sys.argv[1] if len(sys.argv) > 1 else "all"
    if product == "all":
        for name, posts in ALL_PRODUCTS.items():
            print(f"Seeding {len(posts)} posts for '{name}'...")
            ingest_posts(posts, name)
        print("Done: seeded all products")
    else:
        posts = ALL_PRODUCTS.get(product, NOTION_POSTS)
        print(f"Seeding {len(posts)} posts for product: '{product}'...")
        ingest_posts(posts, product)
        print("Done")


if __name__ == "__main__":
    main()
