"""
Seed the vector store with realistic sample posts for demo/testing.
Run: python -m scripts.seed_data notion
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime, timezone, timedelta
from backend.models.post import Post
from backend.ingestion.pipeline import ingest_posts

NOTION_POSTS = [
    Post(
        id="notion_seed_001",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed001",
        title="Notion is way too complicated for new users",
        body="I've tried to get into Notion multiple times and every time I give up after a week. The onboarding just throws you into a blank page with no guidance. I spent 2 hours watching YouTube tutorials just to build a basic task list. Compare this to Todoist where I was productive on day one. The learning curve is absolutely brutal.",
        author="frustrated_user_01",
        score=847,
        created_at=datetime.now(timezone.utc) - timedelta(days=15),
        subreddit="Notion",
        sentiment_score=-0.7,
    ),
    Post(
        id="notion_seed_002",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/productivity/comments/seed002",
        title="The template gallery is overwhelming and useless",
        body="Every time I open Notion's template gallery I get decision paralysis. There are thousands of templates and none of them are exactly what I need. I end up spending more time looking at templates than actually working. I wish there was a simple 'start here' path for new users instead of this giant maze.",
        author="productivity_seeker",
        score=621,
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
        subreddit="productivity",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_003",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="Great concept but mobile experience is terrible",
        body="Love what Notion tries to do but the mobile app is a disaster. It's slow to load, the editor is clunky on phone screens, and half the features from desktop are missing. I've switched to using it only on my laptop because the mobile app frustrates me so much.",
        author="MobileUserJoe",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
        app_id="1232780281",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_004",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed004",
        title="New user here - what's the best way to get started?",
        body="Just signed up for Notion after seeing it everywhere. Opened it and stared at a blank page for 20 minutes. There's no tutorial, no quick win, nothing. I feel like I need a degree to use this thing. How did you all get started? I almost quit immediately.",
        author="newbie_notion",
        score=334,
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
        subreddit="Notion",
        sentiment_score=-0.3,
    ),
    Post(
        id="notion_seed_005",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed005",
        title="Why Notion's onboarding fails — and how to fix it",
        body="Notion is powerful but its onboarding is a perfect example of a product that shows off features instead of delivering value. The first session should give users one clear win. Instead you get a blank canvas and a 47-item template gallery. The drop-off rate on day 1 must be enormous.",
        author="hn_tech_critic",
        score=412,
        created_at=datetime.now(timezone.utc) - timedelta(days=30),
        sentiment_score=-0.4,
    ),
    Post(
        id="notion_seed_006",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed006",
        title="Notion offline mode is basically broken",
        body="I travel for work and Notion is completely useless without internet. I've lost edits three times because I was on a spotty connection. The offline sync is just fundamentally broken. Obsidian does this perfectly with local files. Why can't Notion figure this out?",
        author="travel_worker_22",
        score=512,
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
        subreddit="Notion",
        sentiment_score=-0.8,
    ),
    Post(
        id="notion_seed_007",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="5 stars — changed how I work",
        body="Notion has completely transformed my productivity. Once I got past the initial learning curve it's absolutely incredible. I use it for my personal CRM, project management, notes, and journaling. The flexibility is unmatched. Nothing else comes close.",
        author="PowerUserPaul",
        score=5,
        created_at=datetime.now(timezone.utc) - timedelta(days=3),
        app_id="1232780281",
        sentiment_score=0.9,
    ),
    Post(
        id="notion_seed_008",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/productivity/comments/seed008",
        title="Notion vs Trello for beginners?",
        body="Switched from Trello to Notion last month. Trello has you set up and productive in 5 minutes. Notion took me three weeks to get comfortable with. The power is there but the onboarding gap is massive. Most of my team gave up and went back to Trello. The quick win problem is real — Trello gives you a board immediately, Notion gives you... nothing.",
        author="team_lead_rj",
        score=289,
        created_at=datetime.now(timezone.utc) - timedelta(days=18),
        subreddit="productivity",
        sentiment_score=-0.2,
    ),
    Post(
        id="notion_seed_009",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed009",
        title="Ask HN: Why does everyone at startups use Notion?",
        body="The main appeal is the flexibility — it's basically a Lego set for productivity. But that same flexibility is also its biggest weakness for onboarding. New employees at companies using Notion always struggle for the first month. There should be a simplified mode that hides advanced features until you're ready.",
        author="startup_employee",
        score=156,
        created_at=datetime.now(timezone.utc) - timedelta(days=45),
        sentiment_score=0.1,
    ),
    Post(
        id="notion_seed_010",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed010",
        title="Notion performance is getting worse",
        body="I've been a Notion user for 3 years and the performance has noticeably degraded over the past year. Pages with large databases take 5-8 seconds to load. The app feels sluggish constantly. They keep adding features instead of fixing the core performance. My Notion workspace has become so slow it's affecting my work.",
        author="longtime_user_k",
        score=743,
        created_at=datetime.now(timezone.utc) - timedelta(days=7),
        subreddit="Notion",
        sentiment_score=-0.75,
    ),
    Post(
        id="notion_seed_011",
        source="appstore",
        product="notion",
        url="https://apps.apple.com/us/app/notion/id1232780281",
        title="Too complex, too slow",
        body="I keep coming back hoping it's gotten better and it never has. The app is slow. Everything takes too many clicks. I wanted a note-taking app and got a complexity maze. 2 stars because the idea is good.",
        author="disappointed_app_user",
        score=2,
        created_at=datetime.now(timezone.utc) - timedelta(days=2),
        app_id="1232780281",
        sentiment_score=-0.6,
    ),
    Post(
        id="notion_seed_012",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed012",
        title="The AI features are actually great but nobody talks about it",
        body="People complain about Notion constantly but the AI features that dropped last year are genuinely impressive. Auto-fill databases with AI, summarize pages, translate content — all incredibly useful once set up. The onboarding to AI features is equally bad but the features themselves are fantastic.",
        author="notion_ai_fan",
        score=201,
        created_at=datetime.now(timezone.utc) - timedelta(days=25),
        subreddit="Notion",
        sentiment_score=0.6,
    ),
    Post(
        id="notion_seed_013",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/software/comments/seed013",
        title="Why I quit Notion after 2 years",
        body="The breaking point was realizing I spend more time managing my Notion workspace than actually doing work. It became its own project. The maintenance burden is real — you have to constantly reorganize, update templates, clean up databases. I switched to a simple markdown folder and never looked back. Notion is great for people who enjoy building systems, terrible for people who just want to get things done.",
        author="ex_notion_user",
        score=987,
        created_at=datetime.now(timezone.utc) - timedelta(days=40),
        subreddit="software",
        sentiment_score=-0.5,
    ),
    Post(
        id="notion_seed_014",
        source="hackernews",
        product="notion",
        url="https://news.ycombinator.com/item?id=seed014",
        title="Notion database formulas are a nightmare",
        body="If you try to do anything complex with Notion databases, the formula syntax is opaque and poorly documented. It feels like they designed it for simple use cases and then bolted on complexity. Missing basic operations, no real debugging tools, error messages are useless. Airtable handles this much better.",
        author="formula_frustrated",
        score=88,
        created_at=datetime.now(timezone.utc) - timedelta(days=60),
        sentiment_score=-0.65,
    ),
    Post(
        id="notion_seed_015",
        source="reddit",
        product="notion",
        url="https://reddit.com/r/Notion/comments/seed015",
        title="Best Notion setup for students?",
        body="As a college student Notion is perfect for class notes and project tracking. I've built a GPA tracker, study schedule, and reading list all in one workspace. The learning curve was steep but worth it. It's free for students too which is a huge plus. I've recommended it to everyone in my dorm.",
        author="college_notion_user",
        score=445,
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
        subreddit="Notion",
        sentiment_score=0.75,
    ),
]


def main():
    product = sys.argv[1] if len(sys.argv) > 1 else "notion"
    print(f"Seeding {len(NOTION_POSTS)} posts for product: '{product}'...")
    result = ingest_posts(NOTION_POSTS, product)
    print(f"Done: {result}")


if __name__ == "__main__":
    main()
